name: Go
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: test
        run: go test ./compile/tokenize ./compile/parse ./compile/typecheck